import { 
  Key, 
  Lock, 
  Shield, 
  User, 
  Users, 
  Settings,
  Bell,
  Search,
  Menu,
  Check,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  Plus,
  Minus,
  Edit,
  Trash,
  Copy,
  Download,
  Upload,
  RefreshCw,
  Loader,
  AlertCircle,
  Info,
  CheckCircle,
  HelpCircle,
  ExternalLink,
  Github,
  Twitter,
  Linkedin,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  FileText,
  Folder,
  Database,
  Server,
  Cloud,
  Wifi,
  Sun,
  Moon,
  Monitor,
  Eye,
  EyeOff,
  LogOut,
  LogIn,
  Home,
  LayoutDashboard,
  BarChart3,
  TrendingUp,
  TrendingDown,
  Activity,
  Zap,
  Map,
  Code,
  Terminal,
  GitBranch,
  Building2,
  Cloud as CloudIcon,
  Github as GithubIcon,
  Check as CheckIcon,
  ArrowRight as ArrowRightIcon,
} from 'lucide-react';

// Material Icons to Lucide mapping for easy reference
export const materialToLucide: Record<string, React.ComponentType<{ className?: string }>> = {
  'home': Home,
  'dashboard': LayoutDashboard,
  'key': Key,
  'vpn_key': Key,
  'lock': Lock,
  'shield': Shield,
  'person': User,
  'people': Users,
  'settings': Settings,
  'notifications': Bell,
  'search': Search,
  'menu': Menu,
  'check': Check,
  'check_circle': CheckCircle,
  'cancel': X,
  'expand_more': ChevronDown,
  'expand_less': ChevronUp,
  'chevron_left': ChevronLeft,
  'chevron_right': ChevronRight,
  'arrow_forward': ArrowRight,
  'arrow_back': ArrowLeft,
  'add': Plus,
  'remove': Minus,
  'edit': Edit,
  'delete': Trash,
  'content_copy': Copy,
  'download': Download,
  'upload': Upload,
  'refresh': RefreshCw,
  'sync': RefreshCw,
  'hourglass_empty': Loader,
  'error': AlertCircle,
  'info': Info,
  'help': HelpCircle,
  'open_in_new': ExternalLink,
  'email': Mail,
  'phone': Phone,
  'place': MapPin,
  'event': Calendar,
  'schedule': Clock,
  'description': FileText,
  'folder': Folder,
  'storage': Database,
  'computer': Server,
  'cloud': Cloud,
  'wifi': Wifi,
  'wb_sunny': Sun,
  'nights_stay': Moon,
  'visibility': Eye,
  'visibility_off': EyeOff,
  'exit_to_app': LogOut,
  'login': LogIn,
  'analytics': BarChart3,
  'trending_up': TrendingUp,
  'trending_down': TrendingDown,
  'activity': Activity,
  'flash_on': Zap,
  'map': Map,
  'code': Code,
  'terminal': Terminal,
  'git-branch': GitBranch,
  'apartment': Building2,
};

export {
  Key, Lock, Shield, User, Users, Settings, Bell, Search, Menu, Check, X,
  ChevronDown, ChevronUp, ChevronLeft, ChevronRight, ArrowRight, ArrowLeft,
  Plus, Minus, Edit, Trash, Copy, Download, Upload, RefreshCw, Loader,
  AlertCircle, Info, CheckCircle, HelpCircle, ExternalLink,
  Github, Twitter, Linkedin, Mail, Phone, MapPin, Calendar, Clock,
  FileText, Folder, Database, Server, Cloud, Wifi, Sun, Moon, Monitor,
  Eye, EyeOff, LogOut, LogIn, Home, LayoutDashboard, BarChart3,
  TrendingUp, TrendingDown, Activity, Zap, Map, Code, Terminal, GitBranch,
  Building2, CloudIcon, GithubIcon, CheckIcon, ArrowRightIcon,
};
